; constants.inc - Constant definitions for CityHash

%define k0 0xc3a5c85c97cb3127        ; 64-bit constant k0
%define k1 0xb492b66fbe98f273        ; 64-bit constant k1
%define k2 0x9ae16a3b2f90404f        ; 64-bit constant k2

%define c1 0xcc9e2d51                ; 32-bit constant c1
%define c2 0x1b873593                ; 32-bit constant c2
%define c3 0x12345678                ; 32-bit constant c3

